# Generated by Django 5.2.6 on 2025-09-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memName', models.CharField(max_length=20)),
                ('jobRole', models.CharField(max_length=20)),
                ('mobileNumber', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
