# Generated by Django 5.2.6 on 2025-09-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDM', '0003_member_joined_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=70)),
                ('brandName', models.CharField(max_length=70)),
                ('cost', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('manu_date', models.DateField(null=True)),
                ('exp_date', models.DateField(null=True)),
            ],
        ),
    ]
